name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  # For running the tutorials
  - numpy
  - scipy
  - pooch
  - matplotlib
  - pandas
  - imageio
  # For building the site
  - mystmd
  - nodejs>=20,<21
  - ipython
  - jupyter_server
  - jupyterlab
